<option value="" selected>{{ trans('interiorMaterials.select_interior_materials') }}</option>
<option value="Fabrics">{{ trans('interiorMaterials.fabrics') }}</option>
<option value="Glass">{{ trans('interiorMaterials.glass') }}</option>
<option value="Wood">{{ trans('interiorMaterials.wood') }}</option>
<option value="Stone">{{ trans('interiorMaterials.stone') }}</option>
<option value="Metal">{{ trans('interiorMaterials.metal') }}</option>
<option value="Ceramics and Porcelain">{{ trans('interiorMaterials.ceramics_and_porcelain') }}</option>
<option value="Plastics and Polymers">{{ trans('interiorMaterials.plastics_and_polymers') }}</option>
<option value="Paper and Cardboard">{{ trans('interiorMaterials.paper_and_cardboard') }}</option>
<option value="Natural Fibers">{{ trans('interiorMaterials.natural_fibers') }}</option>
<option value="Composite Materials">{{ trans('interiorMaterials.composite_materials') }}</option>
