<option value="Sunshine Color">{{ trans('sky_color.sunshine_color') }}</option>
<option value="Clear Sky">{{ trans('sky_color.clear_sky') }}</option>
{{-- <option value="Sunrise">Sunrise</option> --}}
<option value="Rainy">{{ trans('sky_color.rainy') }}</option>
<option value="Cloudy">{{ trans('sky_color.cloudy') }}</option>
<option value="Windy">{{ trans('sky_color.windy') }}</option>
<option value="Dawn">{{ trans('sky_color.dawn') }}</option>
<option value="Dusk">{{ trans('sky_color.dusk') }}</option>
<option value="Twilight">{{ trans('sky_color.twilight') }}</option>
<option value="Sunny">{{ trans('sky_color.sunny') }}</option>
<option value="Night">{{ trans('sky_color.night') }}</option>
